# Generated by Django 3.2 on 2022-06-20 22:30

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pubdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pubdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad', models.CharField(blank=True, max_length=45, null=True)),
                ('producto_img', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.funcion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.material')),
            ],
        ),
    ]
