# Generated by Django 3.2 on 2022-06-22 03:24

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaAdmin',
            fields=[
                ('idcuenta', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('identrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField(default='')),
                ('entrega_img', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pubdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('pubdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('producto_img', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('url', models.TextField()),
                ('rango', models.CharField(max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.funcion')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.RESTRICT, related_name='Productos', to='api.material', verbose_name='material')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('carrito_detalle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.carrito')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.producto'),
        ),
    ]
