# Generated by Django 3.2 on 2022-06-20 07:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.IntegerField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaAdmin',
            fields=[
                ('idcuenta', models.IntegerField(db_column='idCuenta', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cuenta-admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('identrega', models.IntegerField(db_column='idEntrega', primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField(blank=True, db_column='fecha-entrega', null=True)),
                ('img_entrega', models.CharField(blank=True, db_column='img-entrega', max_length=45, null=True)),
            ],
            options={
                'db_table': 'entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.IntegerField(db_column='idPedido', primary_key=True, serialize=False)),
                ('fecha_pedido', models.CharField(db_column='fecha-pedido', max_length=45)),
                ('direccion_entrega', models.CharField(db_column='direccion-entrega', max_length=45)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.CharField(blank=True, max_length=45, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria', models.CharField(blank=True, max_length=45, null=True)),
                ('producto_img', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('productocol', models.CharField(blank=True, db_column='Productocol', max_length=45, null=True)),
            ],
        ),
    ]
