# Generated by Django 3.2 on 2022-06-23 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateField(null=True, verbose_name='FechadeEntrega'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
