# Generated by Django 3.2 on 2022-06-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220620_0359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cuentaadmin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entrega',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='productocol',
        ),
    ]
