# Generated by Django 3.2 on 2022-06-20 18:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220620_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='img_entrega',
        ),
        migrations.AddField(
            model_name='entrega',
            name='entrega_img',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='idcarrito',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idcliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuentaadmin',
            name='idcuenta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='identrega',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idpedido',
            field=models.AutoField(db_column='idPedido', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='carrito',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cuentaadmin',
            table=None,
        ),
        migrations.AlterModelTable(
            name='entrega',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pedido',
            table=None,
        ),
    ]
