# Generated by Django 3.2 on 2022-06-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220620_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='entrega_img',
        ),
    ]
